### ISSUE TITLE
Line 2 should  have route Checkout-Begin instead of Login?

### ISSUE THREAD

**Issue by Ad4mSF** [afterpay/afterpay-salesforce-commerce-cloud#10]
https://github.com/afterpay/afterpay-salesforce-commerce-cloud/blob/main/cartridges/int_afterpay_sfra/cartridge/templates/default/cart/checkoutButtons.isml

Current Line 2 says "Checkout-Login" ... and that path is not found.  When reviewing codebase, there is however a path for Begin.  It occurred to me this may have been a typo that was easy to overlook since a Checkout-Login seems like a reasonable route to have.  If this is indeed a mistake, can someone please correct.  On the other hand, if there is supposed to be a login path, is there a different version of where to find that code?

Thank you!!

**Comment by ghatamehta-afterpay** [comment]
Hi @Ad4mSF 
This version of the cartridge doesn't support SFRA 6.0.
https://github.com/afterpay/afterpay-salesforce-commerce-cloud/releases/tag/v23.0.1
In SFRA 5.3.0 and below, the path is "Checkout-Login". [here](https://github.com/SalesforceCommerceCloud/storefront-reference-architecture/blob/v5.3.0/cartridges/app_storefront_base/cartridge/templates/default/cart/checkoutButtons.isml)

Though we are planning to add a cartridge that supports SFRA 6.0 in future release.

Thank you.
